#!/bin/bash
rm memMonitoring.txt
while read NAME2; do
	echo $NAME2 > temp1
	VAL=$(awk '{print $1, $2}' temp1)
	D=$(awk '{print $3}' temp1)
	HOST="$(hostname).memory"
	DAY=$(date +%a)
	MAN=$(date +%b)
	DAYNR=$(date +%d)
	YEAR=$(date +%Y)
	TIMEZ=$(date +%Z)
	S=$(echo " $VAL "|awk -F'|' 'BEGIN{OFS="|"}{("date --date=\""$1"\" +%T") |getline $1;print }')
	TIMESTAMP="$DAY $MAN $DAYNR $S $TIMEZ $YEAR"
	RT2=$(date -d "$TIMESTAMP" +%s%N)
	wait
	echo "$HOST value=$D $RT2" >> memMonitoring.txt
done < $1
