#!/bin/bash
rm cpuMonitoring.txt
while read NAME1; do
	echo $NAME1 > temp
	VAL=$(awk '{print $1, $2}' temp)
	C=$(awk '{print $3}' temp)
	HOST="$(hostname).cpu"
	DAY=$(date +%a)
	MAN=$(date +%b)
	DAYNR=$(date +%d)
	YEAR=$(date +%Y)
	TIMEZ=$(date +%Z)
	S=$(echo " $VAL "|awk -F'|' 'BEGIN{OFS="|"}{("date --date=\""$1"\" +%T") |getline $1;print }')
	TIMESTAMP="$DAY $MAN $DAYNR $S $TIMEZ $YEAR"
	RT=$(date -d "$TIMESTAMP" +%s%N)
	wait
	echo "$HOST value=$C $RT" >> cpuMonitoring.txt
done < $1
