#!/usr/local/bin/Rscript

#print(getwd())
#datas= read.csv('../csv-and-graphs/anova/csv/done/cpu-update.csv')
#datas= read.csv('../csv-and-graphs/anova/comp-csv/done/sent-read.csv')
#datas= read.csv('../csv-and-graphs/csv_files/x_result/amount_cass-delete.csv')
#datas= read.csv('../csv-and-graphs/csv_files/x_result/disk-read-delete.csv')
datas= read.csv('../csv-and-graphs/csv_files/x_result/v_step-disk_.csv')
#print(datas)
stf <- stack(datas)
names(stf) <- c("metric", "architecture")
#print(stf)
res <- aov(metric ~ architecture, data=stf)
summary(res)
tk <- TukeyHSD(res)
print(tk)
#plot(res)
