#!/bin/sh
apt-get update -y
apt-get install -y \
    apt-transport-https -y \
    ca-certificates -y \
    curl -y \
    software-properties-common -y;

# Java 8
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list;
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list;
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886;

# Cassandra
echo "deb http://www.apache.org/dist/cassandra/debian 39x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list;
curl https://www.apache.org/dist/cassandra/KEYS | apt-key add -;

sudo apt-get update -y;
apt-get install oracle-java8-installer -y;
apt-get install cassandra -y;

